---
- name: Provision all
  hosts: all
  become: yes
  tasks:
  - name: Update apt's repository indices
    # Equivalent to 'apt-get update'.
    # https://askubuntu.com/a/222352
    apt:
      update_cache: yes
      cache_valid_time: 3600  # ..seconds = 1 hour
    when: ansible_distribution in ['Ubuntu', 'Debian']


- name: Provision master
  hosts: master
  gather_facts: no
  tasks:
  - name: Be helpful
    debug: msg="Here is where you can add provisioning stuff for the master :)"


- name: Provision slaves
  hosts: slaves
  gather_facts: no
  tasks:
  - name: Be helpful
    debug: msg="Here is where you can add provisioning stuff for slaves :)"