---
- name: Perform full upgrade
  hosts: my-ubuntu
  gather_facts: no
  become: yes
  tasks:
  - name: Do upgrade
    apt:
      update_cache: yes
      upgrade: dist
    register: upgrade
  # https://github.com/ansible/ansible/issues/26521#issuecomment-371142617
  - name: Remove nondownloadable packages from cache
    apt:
      autoclean: yes
    when: upgrade is succeeded
  - name: Remove and purge orphaned packages
    apt:
      autoremove: yes
      purge: yes
    when: upgrade is succeeded

- name: Figure out which snaps are installed
  hosts: my-ubuntu
  gather_facts: no
  become: yes
  tasks:
  - name: Install Snap, if missing
    apt: name=snap
  - name: Read list
    command: snap list
    register: snaps

- name: Install gedit
  hosts: my-ubuntu
  gather_facts: no
  become: yes
  tasks:
  - command: snap install gedit
    when: "'gedit' not in snaps.stdout"