---
- name: Provision all
  hosts: all
  become: yes
  tasks:
  - name: Update apt's repository indices
    apt:
      update_cache: yes
      cache_valid_time: 3600  # ..seconds = 1 hour
    when: ansible_distribution in ['Ubuntu', 'Debian']

- name: Yet another provisioning example
  # May refer to machine names and/or Ansible groups as specified in
  # Vagrantfile, separated by colons.
  # http://docs.ansible.com/ansible/latest/playbooks_intro.html#hosts-and-users
  hosts: my-ubuntu
  gather_facts: no
  tasks:
  - name: Greet
    debug: msg="Hello, World!"